In [11]:
import numpy as np
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m2 = np.array([[4,5],[6,7],[8,9]])

In [12]:
for i in m1:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [13]:
for i in m2:
    print(i)

[4 5]
[6 7]
[8 9]


In [14]:
r = len(m1)
c= len(m2[0])
cr = len(m1[0])

In [15]:
mm=[]
for i in range(r):
    lst=[]
    for j in range(c):
        sum=0
        for k in range(cr):
            sum = sum+m1[i][k]*m2[k][j]
        lst.append(sum)
    mm.append(lst)

for i in mm:
    print(i)

[40, 46]
[94, 109]
[148, 172]


In [17]:
m3=np.matmul(m1,m2)

In [20]:
np.full_like(m3,25)

array([[25, 25],
       [25, 25],
       [25, 25]])