In [1]:
import numpy as np

# Create a One Dimensional Array

In [2]:
x = np.array([1,2,3,4,5])

In [3]:
print(x)

[1 2 3 4 5]


In [4]:
x

array([1, 2, 3, 4, 5])

# Creating a Two Dimensional Array

In [7]:
xmd = np.array([[1,2,3],[4,5,6]],dtype='int8')

In [8]:
print(xmd)

[[1 2 3]
 [4 5 6]]


In [9]:
xmd

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [10]:
xmd[1,1]

5

# Checing Size and Shape
## Size --> Attribute .size
## Shape -- Attribute .shape

In [12]:
xmd.size

6

In [14]:
xmd.shape

(2, 3)

# Indexing and Slicing 

In [16]:
print(xmd[1:,1:])

[[5 6]]


In [17]:
xmd = np.array([[2,3,5],[5,6,7],[7,8,9]])

In [18]:
xmd.shape

(3, 3)

In [19]:
print(xmd)

[[2 3 5]
 [5 6 7]
 [7 8 9]]


In [20]:
print(xmd[1:,:2])

[[5 6]
 [7 8]]


In [21]:
y = np.array([5,7,8,4,5])

In [22]:
print(x)
print(y)

[1 2 3 4 5]
[5 7 8 4 5]


# Arithmetic Operations on Array

In [23]:
print(x+y)

[ 6  9 11  8 10]


In [24]:
print(x*y)

[ 5 14 24 16 25]


In [25]:
print(x*4)

[ 4  8 12 16 20]


In [26]:
z = np.array([1,2,3])

In [28]:
print(x+y)

[ 6  9 11  8 10]


In [33]:
print(xmd)

[[2 3 5]
 [5 6 7]
 [7 8 9]]


In [37]:
xt = xmd.reshape(1,9)

In [38]:
print(xt)

[[2 3 5 5 6 7 7 8 9]]


In [39]:
md_8 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [41]:
print(md_8)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
md_8_new = md_8.reshape(2,2,3)

In [49]:
print(md_8_new)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [50]:
print(x)

[1 2 3 4 5]


In [54]:
z = np.array([[1,2,3,4,5]])

In [55]:
print(z)

[[1 2 3 4 5]]


In [56]:
print(z.reshape(5,1))

[[1]
 [2]
 [3]
 [4]
 [5]]


In [66]:
xn = x.reshape(5,1)

In [58]:
print(x)

[1 2 3 4 5]


In [59]:
print(z)

[[1 2 3 4 5]]


In [60]:
print(x[2])

3


In [61]:
print(z[0,2])

3


In [65]:
print(z[0,2])

3


In [67]:
print(xn)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [75]:
print(x[1],xn[1])

2 [2]


# Indexing 3 Dimensionals Array

In [98]:
xthree = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [99]:
print(xthree.shape)

(2, 2, 3)


In [100]:
print(xthree)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [91]:
xthree

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [92]:
print(xthree[1,0,1])

8


In [93]:
print(xthree[1,1,2])

12


In [94]:
print(xthree[0,1,2])

6


# 4 Dimension Array

In [108]:
x_four  = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])

In [110]:
print(x_four.shape)

(2, 2, 2, 3)


In [112]:
print(x_four[1,1,0,1])

8


# Creating Zero Matrix

In [125]:
z = np.zeros([10,10],dtype='int16')

In [126]:
print(z)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [119]:
y = np.ones([5,2])

In [120]:
print(y)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [121]:
ynew = y.reshape(2,5)

In [122]:
print(ynew)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Concatenating Two Arrays

In [127]:
print(x)

[1 2 3 4 5]


In [129]:
print(z)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [133]:
y = np.ones(5,dtype='int16')

In [134]:
print(y)

[1 1 1 1 1]


In [142]:
z = np.concatenate([[x,y]])

In [143]:
z.shape

(2, 5)