In [1]:
import numpy as np

In [3]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
m1.shape

(3, 3)

In [8]:
m2 = np.zeros((3,3),dtype='int8')

In [9]:
m2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [10]:
m3 = np.ones((3,3),dtype='int16')

In [11]:
m3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [12]:
m4 = np.full((3,3),25)

In [13]:
m4

array([[25, 25, 25],
       [25, 25, 25],
       [25, 25, 25]])

In [14]:
m5 = np.full_like(m4,20)

In [15]:
m5

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [17]:
m6 = np.random.rand(3,3)

In [18]:
m6

array([[0.77927579, 0.45578651, 0.56018179],
       [0.33312741, 0.35287861, 0.58666117],
       [0.89240199, 0.15400118, 0.9280881 ]])

In [48]:
m7 = np.random.randint(0,10,size=(3,3))

In [49]:
m7

array([[9, 1, 9],
       [9, 9, 5],
       [4, 7, 6]])

In [21]:
m8 = m7[1:,1:]

In [22]:
m8

array([[3, 9],
       [2, 4]])

In [23]:
m8[0,0]=25

In [24]:
m8

array([[25,  9],
       [ 2,  4]])

In [25]:
m7

array([[ 3,  7,  7],
       [ 6, 25,  9],
       [ 3,  2,  4]])

In [26]:
m9=m8.copy()

In [27]:
m9

array([[25,  9],
       [ 2,  4]])

In [28]:
m9[0,0]=30

In [29]:
m9

array([[30,  9],
       [ 2,  4]])

In [30]:
m8

array([[25,  9],
       [ 2,  4]])

In [31]:
m7>2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [32]:
m7[m7>4]

array([ 7,  7,  6, 25,  9])

# Broadcasting

In [33]:
m7

array([[ 3,  7,  7],
       [ 6, 25,  9],
       [ 3,  2,  4]])

In [34]:
m7[1:,1:]=[[1,1],[2,2]]

In [42]:
m7

array([[3, 7, 7],
       [6, 1, 1],
       [3, 2, 2]])

In [43]:
m7[0::2,0::2]

array([[3, 7],
       [3, 2]])

In [37]:
m10=np.random.randint(1,10,size=(5,5))

In [41]:
print(m10)
m10[0::2,0::2]

[[1 8 7 2 8]
 [3 6 4 4 3]
 [6 3 3 5 9]
 [8 6 6 5 8]
 [3 6 8 8 3]]


array([[1, 7, 8],
       [6, 3, 9],
       [3, 8, 3]])

# Linear Algebra

In [50]:
m7

array([[9, 1, 9],
       [9, 9, 5],
       [4, 7, 6]])

In [52]:
#Determinent

np.linalg.det(m7)

In [53]:
np.transpose(m7)

array([[9, 9, 4],
       [1, 9, 7],
       [9, 5, 6]])

In [54]:
m7.T

array([[9, 9, 4],
       [1, 9, 7],
       [9, 5, 6]])

In [57]:
m7t = m7.transpose()

In [60]:
print(m7)
print(m7t)

[[9 1 9]
 [9 9 5]
 [4 7 6]]
[[9 9 4]
 [1 9 7]
 [9 5 6]]


In [61]:
# Identity Matrix

In [64]:
m11 = np.identity(3,dtype='int8')

In [65]:
m11

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [67]:
m7i = np.linalg.inv(m7)

In [69]:
m7id = np.matmul(m7,m7i)

In [70]:
m7id.round()

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0., -0.,  1.]])