In [2]:
import numpy as np

def demoFunction(x):
    if(x%2==0):
        return 5
    else:
        return 7

In [3]:
dfv = np.vectorize(demoFunction)

In [4]:
m1 = np.random.randint(1,10,size=(3,3))

In [5]:
m1

array([[8, 4, 5],
       [7, 4, 1],
       [2, 6, 8]])

In [6]:
dfv(m1)

array([[5, 5, 7],
       [7, 5, 7],
       [5, 5, 5]])

# Statistical Values

In [9]:
m1

array([[8, 4, 5],
       [7, 4, 1],
       [2, 6, 8]])

In [10]:
np.mean(m1)

5.0

In [12]:
np.median(m1)

5.0

In [14]:
np.max(m1,axis=0) # Zero is for column and one is for row 

array([8, 6, 8])

In [15]:
np.max(m1,axis=1)

array([8, 7, 8])

In [16]:
np.min(m1)

1

In [18]:
np.min(m1,axis=0)

array([2, 4, 1])

# Traversing an np Array

In [19]:
m1

array([[8, 4, 5],
       [7, 4, 1],
       [2, 6, 8]])

In [20]:
6 in m1

True

In [21]:
0 in m1

False

In [22]:
for x in m1:
    print(x)

[8 4 5]
[7 4 1]
[2 6 8]


In [23]:
for x in m1:
    for y in x:
        print(y)

8
4
5
7
4
1
2
6
8


In [24]:
for x in np.nditer(m1):
    print(x)

8
4
5
7
4
1
2
6
8


In [26]:
m2 = np.array([[[1,2,3],[3,4,5],[5,6,7]]])

In [27]:
m2

array([[[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]]])

In [28]:
for i in np.nditer(m2):
    print(i)

1
2
3
3
4
5
5
6
7
